# Generated by Django 5.1.3 on 2025-01-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
