# Generated by Django 5.1.3 on 2025-01-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
